<?php
error_reporting(0);

$timezone = "Asia/Jakarta";
if(function_exists('date_default_timezone_set')) date_default_timezone_set($timezone);

session_start();
if (empty($_SESSION['username']) AND empty($_SESSION['passuser'])){
  echo "<link href='style.css' rel='stylesheet' type='text/css'>
 <center>Untuk mengakses modul, Anda harus login <br>";
  echo "<a href=../../index.php><b>LOGIN</b></a></center>";
}
else{
error_reporting(0);

require('../../plugin/fpdf17/fpdf.php');
include "../../config/koneksi.php";
include "../../config/confpdf.php";
include "../../config/library.php";
include "../../config/fungsi_indotgl.php";

class PDF extends FPDF
{
var $B;
var $I;
var $U;
var $HREF;

function PDF($orientation='P', $unit='mm', $size='A4')
{
    $this->FPDF($orientation,$unit,$size);
    $this->B = 0;
    $this->I = 0;
    $this->U = 0;
    $this->HREF = '';
}

function WriteHTML($html)
{
    $html = str_replace("\n",' ',$html);
    $a = preg_split('/<(.*)>/U',$html,-1,PREG_SPLIT_DELIM_CAPTURE);
    foreach($a as $i=>$e)
    {
        if($i%2==0)
        {
            if($this->HREF)
                $this->PutLink($this->HREF,$e);
            else
                $this->Write(5,$e);
        }
        else
        {
            if($e[0]=='/')
                $this->CloseTag(strtoupper(substr($e,1)));
            else
            {
                $a2 = explode(' ',$e);
                $tag = strtoupper(array_shift($a2));
                $attr = array();
                foreach($a2 as $v)
                {
                    if(preg_match('/([^=]*)=["\']?([^"\']*)/',$v,$a3))
                        $attr[strtoupper($a3[1])] = $a3[2];
                }
                $this->OpenTag($tag,$attr);
            }
        }
    }
}

function OpenTag($tag, $attr)
{
    if($tag=='B' || $tag=='I' || $tag=='U')
        $this->SetStyle($tag,true);
    if($tag=='A')
        $this->HREF = $attr['HREF'];
    if($tag=='BR')
        $this->Ln(5);
}

function CloseTag($tag)
{
    if($tag=='B' || $tag=='I' || $tag=='U')
        $this->SetStyle($tag,false);
    if($tag=='A')
        $this->HREF = '';
}

function SetStyle($tag, $enable)
{
    $this->$tag += ($enable ? 1 : -1);
    $style = '';
    foreach(array('B', 'I', 'U') as $s)
    {
        if($this->$s>0)
            $style .= $s;
    }
    $this->SetFont('',$style);
}

function PutLink($URL, $txt)
{
    $this->SetTextColor(0,0,255);
    $this->SetStyle('U',true);
    $this->Write(5,$txt,$URL);
    $this->SetStyle('U',false);
    $this->SetTextColor(0);
}
function Footer()
		{
			$this->SetY(-15);
			$this->SetFont('Times','I', 10);
			$this->Cell(280,10,'@ Generated by Sistem Aplikasi Persuratan ',0, 0,'L');
			
		}	
}
		$sql="SELECT * FROM end WHERE id_end='1';";
		$hasil = mysql_query($sql, $id_mysql);
		if(!$hasil)
		die("Gagal3");
		
		$r=mysql_fetch_array($hasil);
		$txt 	= $r[1];
		$kota 	= $r[2];
		$bag 	= $r[3];
		$nbag 	= $r[4];
		$tu 	= $r[5];
		$ntu 	= $r[6];
		$ket 	= $r[7];
		$nket 	= $r[8];
		$tt = $kota.', '.tgl_indo(date("Y m d"));
		
		$html = '<BR>REKAPITULASI<BR><BR>'.$txt;
		$pdf = new PDF();
		$pdf->AddPage('L','Legal');
		$pdf->SetMargins(10, 10, 10);
		$pdf->SetAutoPageBreak(true, 13);
		$pdf->SetFont('Times', '',12);
		$pdf->WriteHTML($html);
		$pdf->SetY(70);
		$pdf->Cell(150,5,'',0,0, 'C');								$pdf->Cell(34,5,'',0,0, 'C');	$pdf->Cell(150,5, $tt ,0,1, 'C');
		$pdf->Cell(150,5,'Kepala Sub. Bagian Pembinaan',0,0, 'C');	$pdf->Cell(34,5,'',0,0, 'C');	$pdf->Cell(150,5,'Kepala Urusan Tata Usaha',0,1, 'C');
		$pdf->Cell(150,10,'',0,0, 'C');								$pdf->Cell(34,10,'',0,0, 'C');	$pdf->Cell(150,10,'',0,1, 'C');
		$pdf->Cell(150,10,'',0,0, 'C');								$pdf->Cell(34,10,'',0,0, 'C');	$pdf->Cell(150,10,'',0,1, 'C');
		$pdf->Cell(150,5,'',0,0, 'C');								$pdf->Cell(34,5,'',0,0, 'C');	$pdf->Cell(150,5,'',0,1, 'C');
		$pdf->Cell(150,5, $bag ,0,0, 'C');							$pdf->Cell(34,5,'',0,0, 'C');	$pdf->Cell(150,5,$tu ,0,1, 'C');
		$pdf->Cell(150,5,$nbag ,0,0, 'C');					$pdf->Cell(34,5,'',0,0, 'C');	$pdf->Cell(150,5,$ntu,0,1, 'C');
		$pdf->Cell(334,10,'',0,1, 'C');
		$pdf->Cell(334,5,'Mengetahui, ',0,1, 'C');
		$pdf->Cell(334,5,'Kepala Kejaksaan Negeri '.$kota,0,1, 'C');
		$pdf->Cell(334,10,'',0,1, 'C');
		$pdf->Cell(334,10,'',0,1, 'C');
		$pdf->Cell(334,5,'',0,1, 'C');
		$pdf->Cell(334,5,$ket,0,1, 'C');
		$pdf->Cell(334,5,$nket,0,1, 'C');
		mysql_close($id_mysql);
		$pdf->Output('Ansanwan-Laporan_'.date("d-m-Y H;m;s").'.pdf', 'I');
}
?>
